const loadProductActions = Object.freeze({
  REQUEST_GET_PRODUCTS: 'REQUEST_GET_PRODUCTS',
  REQUEST_GET_PRODUCTS_SUCCESS: 'REQUEST_GET_PRODUCTS_SUCCESS',
  REQUEST_GET_PRODUCTS_FAILURE: 'REQUEST_GET_PRODUCTS_FAILURE',
});

export { loadProductActions };
